server:
  port: 8102

spring:
  application:
    name: developer02-web
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080