server:
  port: 8101

spring:
  application:
    name: developer01-web
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: localhost:8848