server:
  port: 8002

spring:
  application:
    name: consumer02
  cloud:
    nacos:
      discovery:
        enabled: true
        service: ${spring.application.name}
        server-addr: localhost:8848